spring:
  application:
    name: garbarino
  h2:
    console.enabled: true
app:
  legacyUrl: ${LEGACY_URL}
  cache.ttl: 1000*60*60 #Cacheo por 1 hora
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG